"""Creative seed generation — one source of truth for the whole pipeline.

Both the automated preview builder (generator.py) and the paste-into-Replit
brief (replit_brief.py) need random creative seeds, and they must not drift
apart, so the shell one-liner lives here once.
"""

import subprocess

import config


def design_seed(length=config.SEED_LENGTH):
    """A long random alphanumeric string — the creative seed for one design.

    Generated by a shell one-liner (per the design procedure), with a Python
    fallback so a build never fails over randomness.
    """
    try:
        out = subprocess.run(
            ["bash", "-c",
             f"LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c {int(length)}"],
            capture_output=True, text=True, timeout=10, check=True).stdout.strip()
        if len(out) == length and out.isalnum():
            return out
    except Exception:
        pass
    import secrets, string
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))
